fixed edit mentee form so fields will auto-populate
BloomTech-Labs/village-book-builders-fe-a pull request #2
Opened 2021-02-27 00:20 UTC by jtwillo51

2021-02-27 00:46 UTC, abdimohamud commented on src/components/pages/Headmaster/Mentees/MenteeForm.js
> +  console.log(currentMentee);
Make sure this isn't in production! :)

2021-02-27 00:48 UTC, abdimohamud requested changes
Looks good to me as far as fixing the field, just need to remove that console

2021-02-27 02:11 UTC, Chris-Forrest approved these changes
Other then what Abdi pointed everything looks good keep up the good work

2021-03-02 01:33 UTC, abdimohamud approved these changes

2021-03-02 01:33 UTC, merged